config/routes.rb
Rails.application.routes.draw do
  resources :paginas do
    resources :bets
  end
  devise_for :users
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :user
  belongs_to :pagina
end

app/models/pagina.rb
class Pagina < ApplicationRecord
  belongs_to :user
  has_many :bets
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :paginas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @bets = Bet.all
  end

  def show
  end

  def new
    @pagina = Pagina.find params[:pagina_id]
    @bet = @pagina.bets.build
  end

  def edit
  end

  def create
    @pagina = Pagina.find params[:pagina_id]
    @bet = @pagina.bets.build(bet_params)
    @bet.user_id = current_user.id

    respond_to do |format|
      if @bet.save
        format.html { redirect_to [@pagina, @bet], notice: 'Aposta criada.' }
        format.json { render :show, status: :created, location: [@pagina, @bet] }
      else
        format.html { render :new }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bet.update(bet_params)
        format.html { redirect_to [@pagina, @bet], notice: 'Aposta atualizada.' }
        format.json { render :show, status: :ok, location: [@pagina, @bet] }
      else
        format.html { render :edit }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to bets_url, notice: 'Aposta apagada.' }
      format.json { head :no_content }
    end
  end

  private

    def set_bet
      @bet = Bet.find(params[:id])
    end


    def bet_params
      params.require(:bet).permit(:pagina_id, :time1, :time2, :valor)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  before_action :set_pagina, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @paginas = Pagina.all
  end

  def show
  end

  def new
    @pagina = current_user.paginas.build
  end

  def edit
  end

  def create
    @pagina = current_user.paginas.build(pagina_params)

    respond_to do |format|
      if @pagina.save
        format.html { redirect_to @pagina, notice: 'Pagina criada com sucesso.' }
        format.json { render :show, status: :created, location: @pagina }
      else
        format.html { render :new }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pagina.update(pagina_params)
        format.html { redirect_to @pagina, notice: 'Pagina alterada com sucesso.' }
        format.json { render :show, status: :ok, location: @pagina }
      else
        format.html { render :edit }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pagina.destroy
    respond_to do |format|
      format.html { redirect_to paginas_url, notice: 'Pagina apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

    def set_pagina
      @pagina = Pagina.find(params[:id])
    end


    def pagina_params
      params.require(:pagina).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/bets/_form.html.erb
<%= form_for [@bet.pagina, @bet] do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time1 %>
    <%= f.number_field :time1 %>
  </div>

  <div class="field">
    <%= f.label :time2 %>
    <%= f.number_field :time2 %>
  </div>

  <div class="field">
    <%= f.label :valor %>
    <%= f.text_field :valor %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing Bet</h1>

<%= render 'form', bet: @bet %>

<%= link_to 'Show', [@bet.pagina, @bet] %> |
<%= link_to 'Back', pagina_bets_path %>

app/views/bets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Pagina</th>
      <th>Time1</th>
      <th>Time2</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bets.each do |bet| %>
      <tr>
        <td><%= bet.user %></td>
        <td><%= bet.pagina %></td>
        <td><%= bet.time1 %></td>
        <td><%= bet.time2 %></td>
        <td><%= bet.valor %></td>
        <td><%= link_to 'Show', bet %></td>
        <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
        <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bet', new_pagina_bet_path %>

app/views/bets/new.html.erb
<h1>New Bet</h1>

<%= render 'form', bet: @bet %>

<%= link_to 'Back', pagina_bets_path %>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @bet.user.email %>
</p>

<p>
  <strong>Pagina:</strong>
  <%= @bet.pagina.name %>
</p>

<p>
  <strong>Time1:</strong>
  <%= @bet.time1 %>
</p>

<p>
  <strong>Time2:</strong>
  <%= @bet.time2 %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @bet.valor %>
</p>

<%= link_to 'Edit', edit_pagina_bet_path(@bet) %> |
<%= link_to 'Back', pagina_bets_path %>

app/views/home/index.html.erb
    <div class="app-bar fixed-top darcula" data-role="appbar">
      <a class="app-bar-element branding">AppNet</a>
      <span class="app-bar-divider"></span>
      <ul class="app-bar-menu">
        <li><a href="#">Home</a></li>
        <li><a href="#">Futebol</a></li>
        <li>
          <a href="#" class="dropdown-toggle">Outros</a>
          <ul class="d-menu" data-role="dropdown">
            <li><a href="#">Tênis</a></li>
            <li><a href="#">Basquetebol</a> </li>
            <li><a href="#">Futebol Americano</a> </li>
            <li><a href="#">Beisebol</a> </li>
            <li><a href="#">Voleibol</a> </li>
            <li><a href="#">Roquei no Gelo</a> </li>
          </ul>
        </li>
        <li><a href="#">Contatos</a></li>
      </ul>
    </div>
    <div class="container-fluid" style="margin-top: 50px;">
      <%= image_tag "prediction-page-top-background.png.jpeg" %>
    </div>
    <div class="container">
      <h1 style="color: #f0a30a;">Participe do Bolão.</h1>
      <p style="color: #f0a30a;">
        Escolha um dos resultados possíveis 1, X ou 2 para deixar seus palpites nos jogos.<br>
        Ao final da cartela, veja sua classificação na tabela. Os melhores ganham prêmios.
        <br><br>
        Boa sorte!
      </p>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppNet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-steel">
    <%= yield %>
  </body>
</html>

app/views/paginas/_form.html.erb
<%= form_for(pagina) do |f| %>
  <% if pagina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pagina.errors.count, "error") %> prohibited this pagina from being saved:</h2>

      <ul>
      <% pagina.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paginas/edit.html.erb
<h1>Editar Pagina</h1>

<%= render 'form', pagina: @pagina %>

<%= link_to 'Show', @pagina %> |
<%= link_to 'Back', paginas_path %>

app/views/paginas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paginas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paginas.each do |pagina| %>
      <tr>
        <td><%= pagina.name %></td>
        <td><%= pagina.user.email %></td>
        <td><%= link_to 'Mostrar', pagina %></td>
        <td><%= link_to 'Editar', edit_pagina_path(pagina) %></td>
        <td><%= link_to 'Apagar', pagina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Página', new_pagina_path %>

app/views/paginas/new.html.erb
<h1>Nova Pagina</h1>

<%= render 'form', pagina: @pagina %>

<%= link_to 'Back', paginas_path %>

app/views/paginas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pagina.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @pagina.user.email %>
</p>

<%= link_to 'Edit', edit_pagina_path(@pagina) %> |
<%= link_to 'Back', paginas_path %>